name: Jekyll site CI

on:
  push:
    branches: [ jekyll-build ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: helaili/jekyll-action@v2
      with:
        target_branch: 'jekyll'
        token: ${{ secrets.PAT_TOKEN }}
