name: Jekyll site CI

on:
  push:
    branches: [ jekyll-build ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: helaili/jekyll-action@v2
      with:
        target_branch: 'jekyll'
        target_path: /
        keep_history: true
        token: ${{ secrets.GITHUB_TOKEN }}
